import { useState } from "react";
import { Eye, EyeOff, Maximize2, Minus, Move, Plus } from "lucide-react";
import type { OcrBox } from "../types";

function bounds(polygon: OcrBox["polygon"]) { const xs = polygon.map((point) => point[0]); const ys = polygon.map((point) => point[1]); return { x: Math.min(...xs), y: Math.min(...ys), width: Math.max(...xs) - Math.min(...xs), height: Math.max(...ys) - Math.min(...ys) }; }
export function ImageEvidence({ src, boxes }: { src?: string; boxes: OcrBox[] }) {
  const [showBoxes, setShowBoxes] = useState(true); const [zoom, setZoom] = useState(1); const [selected, setSelected] = useState<OcrBox | null>(null); const [dimensions, setDimensions] = useState({ width: 1, height: 1 }); const [offset, setOffset] = useState({ x: 0, y: 0 }); const [dragStart, setDragStart] = useState<{ x: number; y: number } | null>(null);
  if (!src) return <div className="image-empty">No package image was retained for this inspection.</div>;
  const reset = () => { setZoom(1); setOffset({ x: 0, y: 0 }); };
  return <div className="evidence-viewer"><div className="evidence-toolbar"><span><Move size={15} />Evidence image</span><div><button className="icon-button tiny" onClick={() => setShowBoxes(!showBoxes)} aria-label={showBoxes ? "Hide OCR regions" : "Show OCR regions"}>{showBoxes ? <Eye size={16} /> : <EyeOff size={16} />}</button><button className="icon-button tiny" onClick={() => setZoom(Math.max(0.7, zoom - 0.2))} aria-label="Zoom out"><Minus size={16} /></button><span className="zoom-label">{Math.round(zoom * 100)}%</span><button className="icon-button tiny" onClick={() => setZoom(Math.min(2.5, zoom + 0.2))} aria-label="Zoom in"><Plus size={16} /></button><button className="icon-button tiny" onClick={reset} aria-label="Fit image"><Maximize2 size={16} /></button></div></div><div className="evidence-canvas" onPointerMove={(event) => { if (dragStart) setOffset({ x: event.clientX - dragStart.x, y: event.clientY - dragStart.y }); }} onPointerUp={() => setDragStart(null)} onPointerLeave={() => setDragStart(null)}><div className="evidence-inner" style={{ transform: `translate(${offset.x}px, ${offset.y}px) scale(${zoom})` }} onPointerDown={(event) => setDragStart({ x: event.clientX - offset.x, y: event.clientY - offset.y })}><img src={src} onLoad={(event) => setDimensions({ width: event.currentTarget.naturalWidth, height: event.currentTarget.naturalHeight })} alt="Uploaded packaged commodity" draggable={false} />{showBoxes && boxes.map((box, index) => { const boxBounds = bounds(box.polygon); return <button className={`ocr-box ${selected === box ? "selected" : ""}`} key={`${box.text}-${index}`} onPointerDown={(event) => event.stopPropagation()} onClick={() => setSelected(box)} style={{ left: `${boxBounds.x / dimensions.width * 100}%`, top: `${boxBounds.y / dimensions.height * 100}%`, width: `${boxBounds.width / dimensions.width * 100}%`, height: `${boxBounds.height / dimensions.height * 100}%` }} aria-label={`OCR evidence: ${box.text}`}><span>{box.text}</span></button>; })}</div></div>{selected && <div className="evidence-selection"><b>OCR region selected</b><span>{selected.text}</span><small>Model confidence: {Math.round(selected.confidence * 100)}%</small></div>}<p className="evidence-note">{boxes.length} OCR region{boxes.length === 1 ? "" : "s"} retained from the supplied model. OCR evidence supports review; it is not an independent statutory presentation check.</p></div>;
}
