server {
  listen 80;
  server_name _;

  client_max_body_size 15M;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://api:4000/api/;
  }

  location /uploads/ {
    proxy_pass http://api:4000/uploads/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
