import { ChevronLeft, ChevronRight, ClipboardCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { EmptyState } from "../components/EmptyState";
import { PageHeader } from "../components/AppShell";
import { StatusBadge } from "../components/StatusBadge";
import { api } from "../services/api";
import type { Inspection } from "../types";
import { formatDate } from "../utils";

const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const calendarDate = (value: string) => { const date = new Date(value); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
export function CalendarPage() {
  const [items, setItems] = useState<Inspection[]>([]); const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [selected, setSelected] = useState<string | null>(null); const [error, setError] = useState("");
  useEffect(() => { api.get<{ items: Inspection[] }>("/inspections?page=1&pageSize=100").then((result) => setItems(result.items)).catch((e: Error) => setError(e.message)); }, []);
  const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = (first.getDay() + 6) % 7; const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate();
  const byDate = useMemo(() => items.reduce<Record<string, Inspection[]>>((result, item) => { const key = calendarDate(item.created_at); (result[key] ??= []).push(item); return result; }, {}), [items]);
  const selectedItems = selected ? byDate[selected] ?? [] : [];
  const today = calendarDate(new Date().toISOString());
  return <><PageHeader eyebrow="Inspection operations" title="Inspection calendar" description="Browse the inspection record by day and open any assessment." />{error && <div className="alert error">Unable to load the inspection calendar.</div>}<section className="calendar-layout"><article className="panel calendar-panel"><div className="calendar-heading"><button className="icon-button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label="Previous month"><ChevronLeft size={18} /></button><h2>{monthNames[month.getMonth()]} <span>{month.getFullYear()}</span></h2><button className="icon-button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label="Next month"><ChevronRight size={18} /></button></div><div className="calendar-weekdays">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{Array.from({ length: start + days }, (_, index) => { const day = index - start + 1; if (day < 1) return <span className="calendar-cell blank" key={index} />; const date = `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`; const dayItems = byDate[date] ?? []; return <button className={`calendar-cell ${selected === date ? "selected" : ""} ${today === date ? "today" : ""}`} key={date} onClick={() => setSelected(date)}><span>{day}</span>{dayItems.length > 0 && <div className="calendar-dots">{dayItems.slice(0, 3).map((item) => <i className={`dot-${item.status.toLowerCase()}`} key={item.id} />)}</div>}{dayItems.length > 0 && <small>{dayItems.length}</small>}</button>; })}</div></article><aside className="panel day-panel"><div className="panel-title"><div><p className="eyebrow">Selected day</p><h2>{selected ? formatDate(selected) : "Choose a date"}</h2></div>{selected && <span className="day-count">{selectedItems.length} record{selectedItems.length === 1 ? "" : "s"}</span>}</div>{!selected ? <EmptyState title="Select a date" message="Inspection activity for the selected day will appear here." /> : selectedItems.length === 0 ? <EmptyState title="No inspections" message="There are no records for this date." /> : <div className="day-list">{selectedItems.map((item) => <Link className="day-item" to={`/inspections/${item.id}`} key={item.id}><span className="day-item-icon"><ClipboardCheck size={16} /></span><span><b>{item.product_name}</b><small>{item.id} · {formatDate(item.created_at)}</small></span><StatusBadge status={item.status} compact /></Link>)}</div>}</aside></section></>;
}
