import { useEffect, useState } from "react";
import { CheckCircle2, ChevronLeft, ClipboardCheck, Download, FileText, LoaderCircle, Save, ShieldAlert, TriangleAlert } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { ImageEvidence } from "../components/ImageEvidence";
import { PageHeader } from "../components/AppShell";
import { StatusBadge } from "../components/StatusBadge";
import { assetUrl, api } from "../services/api";
import type { InspectionDetail, Status } from "../types";
import { formatDate, formatPercent, titleStatus } from "../utils";

export function InspectionDetailPage() {
  const { id } = useParams(); const [data, setData] = useState<InspectionDetail | null>(null); const [error, setError] = useState(""); const [notes, setNotes] = useState(""); const [reviewStatus, setReviewStatus] = useState("PENDING"); const [saving, setSaving] = useState(false); const [generating, setGenerating] = useState(false); const [notice, setNotice] = useState("");
  const load = () => { if (id) api.get<InspectionDetail>(`/inspections/${id}`).then((result) => { setData(result); setNotes(result.inspection.reviewer_notes ?? ""); setReviewStatus(result.inspection.review_status ?? "PENDING"); }).catch((e: Error) => setError(e.message)); };
  useEffect(load, [id]);
  const saveReview = async () => { if (!id || !data) return; setSaving(true); try { await api.patch(`/inspections/${id}/review`, { reviewStatus, reviewerNotes: notes }); setNotice("Reviewer assessment saved. Automated evidence remains unchanged."); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save the review."); } finally { setSaving(false); } };
  const generate = async () => { if (!id) return; setGenerating(true); try { await api.post(`/reports/${id}/generate`, { formats: ["pdf", "docx"] }); setNotice("PDF and editable DOCX report generated successfully."); load(); } catch (e) { setError(e instanceof Error ? e.message : "Report generation failed."); } finally { setGenerating(false); } };
  if (error && !data) return <div className="alert error">{error}</div>;
  if (!data) return <div className="detail-loading"><LoaderCircle className="spin" />Loading inspection evidence…</div>;
  const inspection = data.inspection; const score = inspection.score ?? "—";
  const stateCopy: Record<Status, string> = { COMPLIANT: "All required declarations were detected by the automated model.", PARTIAL: "Some mandatory declarations require attention from an authorised reviewer.", NON_COMPLIANT: "Multiple mandatory declarations were not detected by the automated model.", PENDING: "The inspection is awaiting analysis.", ANALYZING: "The image is currently being analysed." };
  return <><Link className="back-link" to="/inspections"><ChevronLeft size={16} />Back to inspections</Link><PageHeader eyebrow="Inspection assessment" title={inspection.id} description={`${inspection.product_name}${inspection.manufacturer ? ` · ${inspection.manufacturer}` : ""}`} actions={<><button className="button secondary" onClick={generate} disabled={generating}><FileText size={16} />{generating ? "Generating…" : "Generate report"}</button><StatusBadge status={inspection.status as Status} /></>} />{error && <div className="alert error">{error}</div>}{notice && <div className="alert success"><CheckCircle2 size={17} />{notice}</div>}
    <section className={`result-banner ${inspection.status.toLowerCase().replace("_", "-")}`}><div><p>Automated compliance result</p><strong>{score}</strong><span>{formatPercent(inspection.compliance_pct)}</span></div><div><StatusBadge status={inspection.status as Status} /><h2>{titleStatus(inspection.status)}</h2><p>{stateCopy[inspection.status as Status]}</p></div><div className="result-meta"><span>Model decision</span><b>Read-only evidence</b></div></section>
    <section className="detail-grid top-detail"><article className="panel evidence-panel"><div className="panel-title"><div><h2>Image inspection</h2><p>Click a region to view detected text and confidence.</p></div></div><ImageEvidence src={assetUrl(data.images[0]?.url)} boxes={data.ocr?.rawBoxes ?? []} /></article><article className="panel declarations-panel"><div className="panel-title"><div><h2>Extracted declarations</h2><p>Presence detected from the supplied OCR model.</p></div></div><div className="declaration-list">{data.declarations.map((item) => <div key={item.id}><span>{item.detected ? <CheckCircle2 size={18} className="check-icon" /> : <TriangleAlert size={18} className="warning-icon" />}</span><div><b>{item.label}</b><small>{item.detected ? "Detected" : "Missing / requires review"}</small></div><strong className={item.detected ? "detected" : "not-detected"}>{item.value || "Not detected"}</strong></div>)}</div><div className="not-evaluated"><ShieldAlert size={17} /><span><b>Font size, placement & readability</b><small>Not evaluated by the current supplied model. Manual review is required.</small></span></div></article></section>
    <section className="panel"><div className="panel-title"><div><h2>Rule validation</h2><p>Official automated results are preserved independently of reviewer assessment.</p></div><span className="technical-label">{inspection.rule_version || "Rule version pending"}</span></div><div className="table-scroll"><table><thead><tr><th>Rule</th><th>Requirement</th><th>Detected value</th><th>Automated scope</th><th>Status</th></tr></thead><tbody>{data.ruleResults.map((rule) => <tr key={rule.id}><td className="mono">{rule.rule_code}</td><td><b>{rule.requirement}</b></td><td>{rule.observed_value || "Not detected"}</td><td><span className="scope-label">{rule.evaluation_scope}</span></td><td><span className={`pass-fail ${rule.status === "PASS" ? "pass" : "fail"}`}>{rule.status === "PASS" ? <CheckCircle2 size={15} /> : <TriangleAlert size={15} />}{rule.status}</span></td></tr>)}</tbody></table></div></section>
    <section className="detail-grid lower-detail"><article className="panel violations-panel"><div className="panel-title"><div><h2>Violation summary</h2><p>{data.violations.length ? `${data.violations.length} automated issue${data.violations.length === 1 ? "" : "s"} requiring follow-up.` : "No automated violations were recorded."}</p></div></div>{data.violations.length === 0 ? <div className="positive-empty"><CheckCircle2 size={21} />No missing declarations detected by the automated model.</div> : <div className="violation-list">{data.violations.map((violation, index) => <details key={violation.id} open={index === 0}><summary><span className="violation-number">{index + 1}</span><span><b>{violation.rule_code} · {violation.requirement}</b><small>{violation.reason}</small></span><span className={`severity ${violation.severity.toLowerCase()}`}>{violation.severity}</span></summary><div className="violation-detail"><p><b>Observed value:</b> {violation.observed_value || "Not detected"}</p><p><b>Evidence/reference:</b> OCR extraction result for this inspection. Verify against package image before enforcement action.</p><p><b>Workflow status:</b> {violation.status}</p></div></details>)}</div>}</article><article className="panel reviewer-panel"><div className="panel-title"><div><h2>Manual review</h2><p>Record a reviewer assessment without overwriting automated evidence.</p></div></div><div className="reviewer-automated"><span>Automated assessment</span><StatusBadge status={inspection.automated_status as Status} compact /></div><label>Reviewer assessment<select value={reviewStatus} onChange={(event) => setReviewStatus(event.target.value)}><option value="PENDING">Pending</option><option value="APPROVED">Approve</option><option value="FURTHER_REVIEW">Mark for further review</option></select></label><label>Reviewer notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Record verified observations, exceptions or next steps." rows={4} /></label><button className="button primary" onClick={saveReview} disabled={saving}><Save size={16} />{saving ? "Saving…" : "Save review"}</button></article></section>
    <section className="panel report-traceability"><div><h2>Reports & traceability</h2><p>Generated reports retain the model, rule and evidence context for this inspection.</p></div><div className="technical-metadata"><span><b>Model</b>{inspection.model_name || "Not analysed"} {inspection.model_version && `v${inspection.model_version}`}</span><span><b>Inference</b>{inspection.device || "—"}</span><span><b>Processing time</b>{inspection.latency_ms != null ? `${inspection.latency_ms} ms` : "—"}</span><span><b>Analysis time</b>{formatDate(inspection.analyzed_at)}</span></div><div className="report-actions">{data.reports.length === 0 ? <button className="button secondary" onClick={generate} disabled={generating}><FileText size={16} />Generate compliance report</button> : data.reports.slice(0, 4).map((report) => <a key={report.id} href={assetUrl(report.url)} target="_blank" rel="noreferrer" className="button secondary"><Download size={16} />Download {report.format}</a>)}</div></section><section className="audit-strip"><ClipboardCheck size={16} /><span>Audit trail: {data.auditLogs.length} recorded event{data.auditLogs.length === 1 ? "" : "s"} · last update {formatDate(data.auditLogs[0]?.created_at)}</span></section></>;
}
