import { useEffect, useState } from "react";
import { Filter, Plus, Search } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState } from "../components/EmptyState";
import { PageHeader } from "../components/AppShell";
import { StatusBadge } from "../components/StatusBadge";
import { api } from "../services/api";
import type { Inspection, Status } from "../types";
import { formatDate, formatPercent } from "../utils";

type Response = { items: Inspection[]; pagination: { page: number; totalPages: number; total: number } };
export function InspectionsPage() {
  const [data, setData] = useState<Response | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [error, setError] = useState(""); const [reload, setReload] = useState(0);
  useEffect(() => { const timer = window.setTimeout(() => { setError(""); api.get<Response>(`/inspections?search=${encodeURIComponent(search)}&status=${status}&page=${page}`).then(setData).catch(() => { setData(null); setError("Unable to load inspections. Try again."); }); }, 200); return () => clearTimeout(timer); }, [search, status, page, reload]);
  if (error) return <><PageHeader eyebrow="Inspection repository" title="Inspections" description="Search and review evidence-backed package assessments." actions={<Link to="/inspections/new" className="button primary"><Plus size={16} />New inspection</Link>} /><div className="alert error" role="alert">{error} <button className="text-button" onClick={() => setReload((value) => value + 1)}>Try again</button></div></>;
  return <><PageHeader eyebrow="Inspection repository" title="Inspections" description="Search and review evidence-backed package assessments." actions={<Link to="/inspections/new" className="button primary"><Plus size={16} />New inspection</Link>} /><section className="panel"><div className="table-toolbar"><label className="field-icon"><Search size={17} /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search ID, product, manufacturer" aria-label="Search inspections" /></label><label className="select-wrap"><Filter size={16} /><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} aria-label="Filter inspection status"><option value="">All statuses</option><option value="COMPLIANT">Compliant</option><option value="PARTIAL">Partial</option><option value="NON_COMPLIANT">Non-compliant</option><option value="PENDING">Pending</option></select></label></div>{!data ? <div className="table-loading">Loading inspections…</div> : data.items.length === 0 ? <EmptyState title="No inspections found" message="Start a new inspection or adjust the active filters." action /> : <><div className="table-scroll"><table><thead><tr><th>Inspection ID</th><th>Product</th><th>Inspection date</th><th>Status</th><th>Compliance</th><th>Violations</th><th>Inspector</th><th /></tr></thead><tbody>{data.items.map((row) => <tr key={row.id}><td className="mono">{row.id}</td><td><b>{row.product_name}</b><small>{row.manufacturer || "Manufacturer not recorded"}</small></td><td>{formatDate(row.created_at)}</td><td><StatusBadge status={row.status as Status} compact /></td><td>{row.compliance_pct == null ? "—" : formatPercent(row.compliance_pct)}</td><td>{row.violation_count ?? 0}</td><td>{row.inspector_name}</td><td><Link className="table-link" to={`/inspections/${row.id}`}>Open</Link></td></tr>)}</tbody></table></div><div className="pagination"><span>{data.pagination.total} total</span><div><button className="button secondary compact" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {data.pagination.page} of {data.pagination.totalPages}</span><button className="button secondary compact" disabled={page === data.pagination.totalPages} onClick={() => setPage(page + 1)}>Next</button></div></div></>}</section></>;
}
