import { useEffect, useState } from "react";
import { AlertCircle, CheckCircle2, Download, ExternalLink, Filter, Search, ShieldCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { EmptyState } from "../components/EmptyState";
import { PageHeader } from "../components/AppShell";
import { StatusBadge } from "../components/StatusBadge";
import { assetUrl, api } from "../services/api";
import type { Status, Violation } from "../types";
import { formatDate, titleStatus } from "../utils";

type Product = { id: string; name: string; manufacturer?: string; category?: string; last_inspection?: string; inspection_count: number; non_compliant_count: number; compliance_status?: Status };
export function ProductsPage() {
  const [items, setItems] = useState<Product[]>([]); const [search, setSearch] = useState("");
  useEffect(() => { const timer = setTimeout(() => api.get<{ items: Product[] }>(`/products?search=${encodeURIComponent(search)}`).then((r) => setItems(r.items)).catch(() => setItems([])), 180); return () => clearTimeout(timer); }, [search]);
  return <><PageHeader eyebrow="Product repository" title="Products" description="Products grouped across inspection and compliance history." /><section className="panel"><div className="table-toolbar"><label className="field-icon"><Search size={17} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search product or manufacturer" /></label></div>{items.length === 0 ? <EmptyState title="No products found" message="Products are created when an inspection is started." /> : <div className="table-scroll"><table><thead><tr><th>Product</th><th>Manufacturer</th><th>Category</th><th>Last inspection</th><th>Status</th><th>Inspection count</th><th>Violations</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><b>{item.name}</b></td><td>{item.manufacturer || "—"}</td><td>{item.category || "—"}</td><td>{formatDate(item.last_inspection)}</td><td>{item.compliance_status ? <StatusBadge status={item.compliance_status} compact /> : "—"}</td><td>{item.inspection_count}</td><td>{item.non_compliant_count}</td><td><Link className="table-link" to={`/products/${item.id}`}>Open</Link></td></tr>)}</tbody></table></div>}</section></>;
}

export function ProductDetailPage() {
  const { id } = useParams(); const [data, setData] = useState<{ product: Product; inspections: Array<{ id: string; created_at: string; status: Status; score?: string; compliance_pct?: number; inspector_name: string }> } | null>(null);
  useEffect(() => { if (id) api.get<typeof data>(`/products/${id}`).then((result) => setData(result!)).catch(() => setData(null)); }, [id]);
  if (!data) return <div className="detail-loading">Loading product history…</div>;
  return <><Link className="back-link" to="/products">← Back to products</Link><PageHeader eyebrow="Product overview" title={data.product.name} description={`${data.product.manufacturer || "Manufacturer not recorded"}${data.product.category ? ` · ${data.product.category}` : ""}`} /><section className="kpi-grid product-kpis"><article className="kpi-card"><p>Inspection count</p><strong>{data.inspections.length}</strong></article><article className="kpi-card"><p>Latest compliance status</p><strong className="small-stat">{titleStatus(data.inspections[0]?.status)}</strong></article><article className="kpi-card"><p>Non-compliant assessments</p><strong>{data.inspections.filter((i) => i.status === "NON_COMPLIANT").length}</strong></article></section><section className="panel"><div className="panel-title"><div><h2>Inspection history</h2><p>Evidence-led assessment record for this product.</p></div></div>{data.inspections.length === 0 ? <EmptyState /> : <div className="table-scroll"><table><thead><tr><th>Inspection ID</th><th>Date</th><th>Status</th><th>Score</th><th>Inspector</th><th /></tr></thead><tbody>{data.inspections.map((i) => <tr key={i.id}><td className="mono">{i.id}</td><td>{formatDate(i.created_at)}</td><td><StatusBadge status={i.status} compact /></td><td>{i.score ?? "—"}</td><td>{i.inspector_name}</td><td><Link className="table-link" to={`/inspections/${i.id}`}>Open</Link></td></tr>)}</tbody></table></div>}</section></>;
}

export function ViolationsPage() {
  const [items, setItems] = useState<Violation[]>([]); const [status, setStatus] = useState(""); const [severity, setSeverity] = useState(""); const [updating, setUpdating] = useState("");
  const load = () => api.get<{ items: Violation[] }>(`/violations?status=${encodeURIComponent(status)}&severity=${encodeURIComponent(severity)}`).then((r) => setItems(r.items)).catch(() => setItems([]));
  useEffect(() => { load(); }, [status, severity]);
  const update = async (id: string, nextStatus: string) => { setUpdating(id); try { await api.patch(`/violations/${id}`, { status: nextStatus }); load(); } finally { setUpdating(""); } };
  return <><PageHeader eyebrow="Follow-up management" title="Violations" description="Manage automated declaration exceptions through a traceable review workflow." /><section className="panel"><div className="table-toolbar"><label className="select-wrap"><Filter size={16} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All workflow statuses</option><option>Open</option><option>Under Review</option><option>Resolved</option></select></label><label className="select-wrap"><Filter size={16} /><select value={severity} onChange={(e) => setSeverity(e.target.value)}><option value="">All severity levels</option><option>High</option><option>Medium</option><option>Low</option></select></label></div>{items.length === 0 ? <EmptyState title="No violations found" message="Automated declaration exceptions will appear here after analysis." /> : <div className="table-scroll"><table><thead><tr><th>Violation ID</th><th>Inspection</th><th>Product</th><th>Rule</th><th>Violation type</th><th>Severity</th><th>Detected date</th><th>Workflow status</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td className="mono short-id">{item.id}</td><td><Link className="table-link" to={`/inspections/${item.inspection_id}`}>{item.inspection_id}</Link></td><td>{item.product_name}</td><td>{item.rule_code}</td><td><b>{item.requirement}</b></td><td><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span></td><td>{formatDate(item.created_at)}</td><td><select className="inline-select" value={item.status} disabled={updating === item.id} onChange={(e) => update(item.id, e.target.value)}><option>Open</option><option>Under Review</option><option>Resolved</option></select></td></tr>)}</tbody></table></div>}</section></>;
}

type Report = { id: string; inspection_id: string; format: string; storage_key: string; created_at: string; product_name: string; status: Status };
export function ReportsPage() {
  const [items, setItems] = useState<Report[]>([]); useEffect(() => { api.get<{ items: Report[] }>("/reports").then((r) => setItems(r.items)).catch(() => setItems([])); }, []);
  return <><PageHeader eyebrow="Official records" title="Reports" description="Generated PDF and editable DOCX compliance reports." /><section className="panel">{items.length === 0 ? <EmptyState title="No reports generated" message="Generate a compliance report from a completed inspection." /> : <div className="table-scroll"><table><thead><tr><th>Report ID</th><th>Inspection</th><th>Product</th><th>Format</th><th>Compliance status</th><th>Generated</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td className="mono short-id">{item.id}</td><td><Link className="table-link" to={`/inspections/${item.inspection_id}`}>{item.inspection_id}</Link></td><td>{item.product_name}</td><td><span className="file-type">{item.format}</span></td><td><StatusBadge status={item.status} compact /></td><td>{formatDate(item.created_at)}</td><td><a className="table-link" href={assetUrl(`/reports/${item.storage_key}`)} target="_blank" rel="noreferrer"><Download size={14} />Download</a></td></tr>)}</tbody></table></div>}</section></>;
}

type Rule = { key: string; code: string; requirement: string; automatedCheck: string; manualReview: string; evaluation: string; unsupportedChecks: string[] };
export function RulesPage() {
  const [items, setItems] = useState<Rule[]>([]); useEffect(() => { api.get<{ items: Rule[] }>("/rules").then((r) => setItems(r.items)).catch(() => setItems([])); }, []);
  return <><PageHeader eyebrow="Regulatory reference" title="Supported rules" description="Versioned automated checks and the explicit boundaries of the supplied model." /><section className="rules-grid">{items.map((rule) => <article className="panel rule-card" key={rule.key}><div className="rule-heading"><span>{rule.code}</span><b>{rule.requirement}</b></div><div><small>Automated check</small><p>{rule.automatedCheck}</p></div><div><small>Manual review required</small><p>{rule.manualReview}</p></div><div className="not-evaluated"><AlertCircle size={16} /><span><b>Not currently evaluated</b><small>{rule.unsupportedChecks.join(" · ")}</small></span></div></article>)}</section><section className="panel reference-note"><ShieldCheck size={20} /><div><h2>Evidence interpretation</h2><p>The application records the supplied model’s declaration-presence outcomes. It does not invent regulatory requirements or represent readability, placement, or statutory font-size as an automated pass.</p></div></section></>;
}

export function SettingsPage() { return <><PageHeader eyebrow="Administration" title="System settings" description="Deployment-aware configuration boundaries for this installation." /><section className="settings-grid"><article className="panel"><h2>Roles & access</h2><p>Authentication is adapter-ready for OIDC/JWT integration. Supported roles are Administrator, Enforcement Officer, Reviewer, and Read Only.</p><span className="technical-label">Identity provider configuration required in production</span></article><article className="panel"><h2>Inference service</h2><p>The browser communicates only with the Node API. The Python RapidOCR/ONNX service remains internal and exposes model device information only in inspection metadata.</p><span className="technical-label">CPU with automatic CUDA detection</span></article><article className="panel"><h2>Data retention</h2><p>Inspection images, OCR evidence, automated outcomes, manual review, reports, and audit events are retained as separate records for traceability.</p><span className="technical-label">Local storage configuration</span></article><article className="panel"><h2>Security controls</h2><p>Input validation, image signature checking, file-size limits, rate limiting, CORS, security headers, role gates, and audit logging are applied by the API.</p><span className="technical-label">Review deployment environment variables</span></article></section></>;
}
