import { Accessibility, CheckCircle2, Info, Moon, ScanLine, Sun, Type } from "lucide-react";
import { useEffect, useState } from "react";
import { PageHeader } from "../components/AppShell";
import { applyAccessibility, broadcastPreferences, defaultAccessibility, defaultInspectionPreferences, readPreferences, readTheme, setThemePreference, type AccessibilityPreferences, type InspectionPreferences, type ThemePreference } from "../preferences";

function Switch({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (checked: boolean) => void }) {
  return <div className="setting-row"><div className="setting-row-copy"><b>{label}</b><span>{description}</span></div><button className={`preference-switch ${checked ? "on" : ""}`} role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)}><span>{checked ? "ON" : "OFF"}</span><i /></button></div>;
}

export function SettingsPage() {
  const [theme, setTheme] = useState<ThemePreference>(readTheme);
  const [accessibility, setAccessibility] = useState<AccessibilityPreferences>(() => readPreferences("metrologyguard-accessibility", defaultAccessibility));
  const [inspection, setInspection] = useState<InspectionPreferences>(() => readPreferences("metrologyguard-inspection", defaultInspectionPreferences));
  useEffect(() => { const sync = () => { setTheme(readTheme()); setAccessibility(readPreferences("metrologyguard-accessibility", defaultAccessibility)); setInspection(readPreferences("metrologyguard-inspection", defaultInspectionPreferences)); }; window.addEventListener("metrologyguard-preferences-change", sync); return () => window.removeEventListener("metrologyguard-preferences-change", sync); }, []);
  const changeTheme = (value: ThemePreference) => { setTheme(value); setThemePreference(value); };
  const changeAccessibility = (key: keyof AccessibilityPreferences, value: boolean) => { const next = { ...accessibility, [key]: value }; setAccessibility(next); localStorage.setItem("metrologyguard-accessibility", JSON.stringify(next)); applyAccessibility(next); broadcastPreferences(); };
  const changeInspection = (key: keyof InspectionPreferences, value: boolean) => { const next = { ...inspection, [key]: value }; setInspection(next); localStorage.setItem("metrologyguard-inspection", JSON.stringify(next)); broadcastPreferences(); };
  return <><PageHeader eyebrow="Workspace preferences" title="Settings" description="Manage your workspace preferences and accessibility." /><div className="settings-layout">
    <section className="settings-section panel"><div className="settings-section-heading"><span className="settings-icon"><Sun size={18} /></span><div><h2>Appearance</h2><p>Choose how MetrologyGuard looks across the application.</p></div></div><div className="theme-options"><button className={theme === "light" ? "selected" : ""} onClick={() => changeTheme("light")}><Sun size={16} />Light</button><button className={theme === "dark" ? "selected" : ""} onClick={() => changeTheme("dark")}><Moon size={16} />Dark</button><button className={theme === "system" ? "selected" : ""} onClick={() => changeTheme("system")}><span className="system-icon">◐</span>System</button></div></section>
    <section className="settings-section panel"><div className="settings-section-heading"><span className="settings-icon"><Accessibility size={18} /></span><div><h2>Accessibility</h2><p>Adjust the interface for easier reading, navigation, and inspection.</p></div></div><div className="settings-rows"><Switch label="Larger text" description="Increase text size across the application." checked={accessibility.largerText} onChange={(value) => changeAccessibility("largerText", value)} /><Switch label="High contrast" description="Increase contrast between text, controls, and backgrounds." checked={accessibility.highContrast} onChange={(value) => changeAccessibility("highContrast", value)} /><Switch label="Larger buttons" description="Increase the size of interactive controls." checked={accessibility.largerButtons} onChange={(value) => changeAccessibility("largerButtons", value)} /><Switch label="Reduced animations" description="Reduce motion and transition effects throughout the application." checked={accessibility.reducedMotion} onChange={(value) => changeAccessibility("reducedMotion", value)} /></div></section>
    <section className="settings-section panel"><div className="settings-section-heading"><span className="settings-icon"><ScanLine size={18} /></span><div><h2>Inspection preferences</h2><p>Choose which evidence details are most useful during review.</p></div></div><div className="settings-rows"><Switch label="Show OCR confidence" description="Display confidence values when viewing detected OCR regions." checked={inspection.showOcrConfidence} onChange={(value) => changeInspection("showOcrConfidence", value)} /><Switch label="Show evidence details by default" description="Open the evidence detail panel when an OCR region is selected." checked={inspection.showEvidenceDetails} onChange={(value) => changeInspection("showEvidenceDetails", value)} /></div></section>
    <section className="settings-section panel"><div className="settings-section-heading"><span className="settings-icon"><Info size={18} /></span><div><h2>Application</h2><p>Product information for this installation.</p></div></div><div className="app-info-grid"><div><span>Product</span><b>MetrologyGuard</b></div><div><span>Purpose</span><b>AI-powered packaged commodity compliance</b></div><div><span>Problem statement</span><b>SIH 2026 — 26034</b></div><div><span>Version</span><b>1.0.0</b></div></div></section>
    <section className="settings-section panel about-section"><div className="settings-section-heading"><span className="settings-icon"><CheckCircle2 size={18} /></span><div><h2>About</h2><p>MetrologyGuard is an AI-powered packaged commodity compliance and inspection platform.</p></div></div><div className="about-note"><Type size={16} /><span>Built to help inspection teams turn package images into clear, evidence-backed compliance records.</span></div></section>
  </div></>;
}
